# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_crm', '0002_auto_20171020_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='role',
            new_name='roles',
        ),
    ]
