# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_crm', '0003_auto_20171020_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='常用邮箱'),
        ),
        migrations.AddField(
            model_name='customer',
            name='id_card',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
