# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_crm', '0004_auto_20171022_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='常用邮箱'),
        ),
    ]
